# Generated by Django 3.2 on 2021-04-22 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='proposed', max_length=255)),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_swaps', to='books.book')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to='books.book')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_swaps', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
