# Generated by Django 3.2 on 2021-04-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
